version: '3'
services:
  app:
    container_name: kettle
    ports:
      - "8888:8888"
    network_mode: host
    build: src/
    command: >
      sh -c "pip install -r requirements.txt
      && python main.py"
